version: '3.3'

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

services:
  nginx:
    image: "nginx"
    depends_on:
      - testserver
      - tomcat7
      - tomcat8
      - ssoclient
    ports:
      - 80:80
    networks:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  tomcat7:
    image: tomcat:renamed-context-7
    environment:
        - CONTEXT_NAME=tomcat7
    networks:
      - frontend

  tomcat8:
    image: tomcat:renamed-context-8.0
    environment:
        - CONTEXT_NAME=tomcat8
    networks:
      - frontend

  testserver:
    image: groovy:2.4.11
    command: groovy /scripts/Server.groovy
    volumes:
      - ./testserver:/scripts
    networks:
      - frontend

  ssoclient:
    image: gradle:alpine
    command: gradle bootRun
    volumes:
      - ./ssoclient:/project
      - ${HOME}/.gradle:/home/gradle/.gradle
    working_dir: /project
    networks:
      - frontend
