---
- name: Configure CI Server
  hosts: ci-server
  become: true
  vars:
    jenkins_plugins: 
      - ansicolor
      - build-timeout
      - email-ext
      - envinject
      - extra-columns
      - git
      - gradle
      - grails
      - groovy
      - heavy-job
      - job-dsl
      - progress-bar-column-plugin
      - subversion
      - ssh-agent
      - ssh-slaves 
      - swarm
      - timestamper
      - workflow-aggregator
      - ws-cleanup
    jenkins_executors: 0 
    jenkins_admin_password: 4f5c4b967e5a478d908b76f2b22f130d
    jenkins_admin_password_file: "/var/lib/jenkins/secrets/initialAdminPassword"
  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.svn }
    - { role: geerlingguy.java }
    - { role: geerlingguy.jenkins }
