#!/usr/bin/env bash
docker pull alpine
docker pull amazonlinux
docker pull bash
docker pull busybox
docker pull cassandra
docker pull centos
docker pull centos
docker pull debian
docker pull docker
docker pull drupal
docker pull elasticsearch
docker pull fedora
docker pull freenas/plex
docker pull golang
docker pull haproxy
docker pull hello-world
docker pull httpd
docker pull java
docker pull jenkins
docker pull jhipster
docker pull logstash
docker pull maven
docker pull memcached
docker pull mongo
docker pull mysql
docker pull nginx
docker pull nginx
docker pull node
docker pull openjdk
docker pull oraclelinux
docker pull php
docker pull postgres
docker pull redis
docker pull registry
docker pull sonarqube
docker pull tomcat
docker pull ubuntu