package:
  docker:
    installed: true
    versions:
      - 18.06.1ce
  git:
    installed: true
    versions:
      - 2.17.2
  gzip:
    installed: true
    versions:
      - "1.5"
  hostname:
    installed: true
    versions:
      - "3.13"
  subversion:
    installed: true
    versions:
      - 1.9.9
  tar:
    installed: true
    versions:
      - "1.26"
  unzip:
    installed: true
    versions:
      - "6.0"
  wget:
    installed: true
    versions:
      - "1.14"
  which:
    installed: true
    versions:
      - "2.20"
service:
  docker:
    enabled: false
    running: false
  ssh:
    enabled: false
    running: false
  sshd:
    enabled: false
    running: false
command:
  aws --version:
    exit-status: 0
    stdout: []
    stderr:
      - aws-cli/1.
    timeout: 10000
  helm version:
    exit-status: 1
    stdout:
      - 'Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4",
      GitTreeState:"clean"}'
    stderr:
      - 'Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller:
      dial tcp 127.0.0.1:8080: connect: connection refused'
    timeout: 10000
  java -version:
    exit-status: 0
    stdout: []
    stderr:
      - java version "1.8.0_172"
      - Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
      - Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
    timeout: 10000
  kubectl version:
    exit-status: 1
    stdout:
      - 'Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b",
      GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8",
      Compiler:"gc", Platform:"linux/amd64"}'
    stderr:
      - The connection to the server localhost:8080 was refused - did you specify the
        right host or port?
    timeout: 10000
  packer --version:
    exit-status: 0
    stdout:
      - 1.4.1
    stderr: []
    timeout: 10000
  terraform --version:
    exit-status: 0
    stdout:
      - Terraform v0.11.10
      - Your version of Terraform is out of date! The latest version
      - is 0.12.1. You can update by downloading from www.terraform.io/downloads.html
    stderr: []
    timeout: 10000
